@startuml
class client <<entity>> {
    - idClient: int
    - civilite: str(10)
    - nom: str(100)
    - prenom: str(100)
    - adresse: str(255)
    - ville: str(150)
    - cp: str(8)
    - mail: str(255)
    - tel: str(15)
}

class clientManager <<repository>> {
    - createClient()
    - readClient()
    - updateClient()
    - deleteClient()
}

class commandes <<entity>> {
    - id: int
    - date: date
    - estPayee: tinyint(1)
    - estExpediee: tinyint(1)
    - client: int
}

class commandsManager <<repository>> {
    - createCommand()
    - readCommand()
    - updateCommand()
    - deleteCommand()
}

class ligneCmd <<entity>> {
    - produit: int
    - commande: int
    - quantite: int
}

class produits <<entity>> {
    - idProduit: int
    - designation: text
    - description: text
    - dateAjout: datetime
    - qte: int
    - prix: decimal(6.2)
    - fichierImage: str(255)
    - pk_fournisseur: int
}

class productsManager <<repository>> {
    - createProduct()
    - readProduct()
    - updateProduct()
    - deleteProduct()
}

client "1  " <-- "0..*  " commandes
commandes "1  " -- "1..*  " ligneCmd
ligneCmd "1..*  " -- "1..*  " produits

clientManager "1..*" .> client
commandsManager "1..*" .> commandes
productsManager "1..*" .> produits

@enduml